---
title: "Climate Statistics FAQ"
---

Perhaps the single largest distinguisher between climate statics and other areas of spatiotemporal statistics is the heavy reliance on physics-based climate models. These models are complicated, so I've found it tricky to figure out how to work with them in a principled way.

The term "FAQ" in the website title is a bit misleading -- these questions considered here are only "frequently asked" in the sense that I've frequently asked them them. This website is a compilation of notes that I've compiled throughout grad school, along with some resources that have helped me understand them.

The goal of these notes is to provide a quick, easy to understand overview of the techniques being used. I use them to remind myself of the key ideas whenever I revisit these ideas. My approach was inspired by Richard Feynman, who famously kept a few simple examples in his head to run through whenever he encountered a new idea, and by Jeopardy champion James Holzhauer, who credits his quick recall to reading a lot of children's books.

